# Generated by Django 2.1.7 on 2019-04-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity_units',
            field=models.CharField(max_length=200),
        ),
    ]
