# Generated by Django 2.1.7 on 2019-04-06 17:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingredients', '0003_ingredientinstance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientInstance',
            new_name='UserIngredient',
        ),
    ]
