# Generated by Django 2.1.7 on 2019-04-07 21:39

from django.db import migrations, models
import ingredients.models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_auto_20190406_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='useringredient',
            name='exp_date',
            field=models.DateField(blank=True, default=ingredients.models.one_month_from_today, null=True),
        ),
    ]
