# Generated by Django 2.1.7 on 2019-04-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mealType', models.CharField(choices=[('BRFST', 'Breakfast'), ('LNCH', 'Lunch'), ('DNR', 'Dinner')], max_length=5)),
                ('mealStyle', models.CharField(choices=[('IT', 'Italian'), ('AM', 'American'), ('AS', 'Asian'), ('FR', 'French')], max_length=2)),
                ('askANeighbor', models.BooleanField()),
            ],
        ),
    ]
