# Generated by Django 2.1.7 on 2019-04-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0006_auto_20190420_1405'),
        ('recommender', '0004_searchmodel_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchmodel',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='searchmodel',
            name='ingredients',
            field=models.ManyToManyField(to='ingredients.UserIngredient'),
        ),
    ]
